# Generated by Django 3.2.8 on 2021-11-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_review',
            name='poster',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
