# Generated by Django 3.2.8 on 2021-11-14 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0002_movie_review_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie_review',
            options={'ordering': ['-posted_on']},
        ),
    ]
